name: fyp
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - freetype=2.10.4
  - jpeg=9d
  - lcms2=2.12
  - libpng=1.6.37
  - libtiff=4.2.0
  - lz4-c=1.9.3
  - olefile=0.46
  - openssl=1.1.1j
  - pillow=8.1.0
  - pip=21.0.1
  - pytesseract=0.3.7
  - python=3.9.1
  - python_abi=3.9
  - pywin32=228
  - setuptools=52.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tzdata=2020f
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.8
  - pip:
    - keyboard==0.13.5
